apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: test-annotations-dfrs
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: test-annotations-dfrs
    app.kubernetes.io/part-of: build-suite-test-application-shav
  name: test-annotations-dfrs
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: my-nginx
      app.kubernetes.io/instance: test-annotations-dfrs
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: my-nginx
        app.kubernetes.io/instance: test-annotations-dfrs
    spec:
      containers:
      - image: quay.io/tnevrlka-test/build-e2e-edmn-tenant/build-suite-test-application-shav/test-annotations-dfrs@sha256:8596082117f138eaec34efff55787d6239a55803b7a6690deb91358f2789a6cf
        name: my-nginx
        ports:
        - containerPort: 8080
          name: http
          protocol: TCP
        - containerPort: 8081
        resources:
          limits:
            cpu: 500m
            memory: 1Gi
status: {}
